QuotationApp.Web/Controllers/KnockoutGridController.cs
using QuotationApp.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace QuotationApp.Web.Controllers
{
    public class KnockoutGridController : Controller
    {
        // GET: KnockoutGrid
        public ActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Index2(IEnumerable<QuotationIndexVm> quos)
        {
            return View();
        }
    }
}

QuotationApp.Web/Controllers/QuotationController.cs
using QuotationApp.Core.Common;
using QuotationApp.Core.Entities;
using QuotationApp.Core.Specifications;
using QuotationApp.Infrastructure.BusinessLayer;
using QuotationApp.Infrastructure.DataLayer;
using QuotationApp.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using System.Security.Principal;

namespace QuotationApp.Web.Controllers
{
    [Authorize]
    public class QuotationController : Controller
    {
        private readonly ApplicationDbContext _db;
        private readonly GenericRepository<Quotation> _repo;
        private readonly ICurrentUserService _curUserService;
        public QuotationController(ApplicationDbContext db)
        {
            _db = db;
        }
        public QuotationController()
        {
            //poor man's IOC for now
            _db = new ApplicationDbContext(System.Web.HttpContext.Current.User.Identity.Name);
            _repo = new GenericRepository<Quotation>(_db);
            _curUserService = new CurrentUserService(System.Web.HttpContext.Current.User.Identity);
            
        }


        public ActionResult Index()
        {
            
            IQueryable<QuotationIndexVm2> model = from q in _repo.GetAll()
                                                 orderby q.Id
                                                 select new QuotationIndexVm2
                                                 {
                                                    Id = q.Id,
                                                    Product_Id = q.Product_Id,
                                                    Product_Description = q.Product_Description,
                                                    MinOrderQty = q.MinOrderQty,
                                                    QuotedPrice = q.QuotedPrice,
                                                    CustomerName = q.Customer.Name,
                                                    CustomerReference = q.CustomerReference,
                                                    
                                                    Status = q.Status,
                                                    CreateDate = DbFunctions.TruncateTime(q.CreateDate),
                                                    CreatedBy = q.CreatedBy,
                                                 };
            ViewBag.PageSize = 10;
            
            return View(model);
        }

        [HttpGet]
        public ActionResult Delete(int id)
        {
            var model = (from q in _db.Quotations
                         where q.Id == id
                         select new QuotationDeleteVm()
                         {
                             Id = q.Id,
                             Product_Id = q.Product_Id,
                             Product_Description = q.Product_Description,
                             QuotedPrice = q.QuotedPrice,
                             CreatedBy = q.CreatedBy,
                             CreatedDate = q.CreateDate,
                         }).FirstOrDefault();

            return View(model);
        }

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            var model = _db.Quotations.Find(id);
            if (model == null)
            {
                return HttpNotFound();
            }
            _db.Quotations.Remove(model);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Edit(int id)
        {
            var model = (from q in _db.Quotations
                        where q.Id == id
                        select new QuotationEditVm()
                        {
                            Id = q.Id,
                            Product_Id = q.Product_Id,
                            Product_Description = q.Product_Description,
                            QuotedPrice = q.QuotedPrice,
                            MinOrderQty = q.MinOrderQty,
                            UnitOfMeasure = (QuotationApp.Core.Common.Enumerations.UnitOfMeasure)q.UnitOfMeasure,
                            Customer_Id = q.Customer_Id,
                            CustomerReference = q.CustomerReference,
                            Comments = q.Comments,
                            AttachmentFileName = q.AttachmentFileName,
                            CreatedBy = q.CreatedBy,
                            CreatedDate = q.CreateDate,
                        }).FirstOrDefault();

            model.CustomerSelectList = new SelectList(_db.Customers.AsQueryable(), "Id", "Name");     
            return View(model);
        }

        [HttpPost]
        public ActionResult Edit(QuotationEditVm quoteVm)
        {
            //we'll move this mess to a service
            //AmazonS3FileService fileService = new AmazonS3FileService(_curUserService);
            if (ModelState.IsValid)
            {
                var model = new Quotation()
                {
                    Id = quoteVm.Id,
                    Product_Id = quoteVm.Product_Id,
                    Product_Description = quoteVm.Product_Description,
                    QuotedPrice = quoteVm.QuotedPrice,
                    Customer_Id = quoteVm.Customer_Id,
                    MinOrderQty = quoteVm.MinOrderQty,
                    UnitOfMeasure = (int)quoteVm.UnitOfMeasure,
                    CustomerReference = quoteVm.CustomerReference,
                    Comments = quoteVm.Comments,
                    Status = quoteVm.Status.GetDescription(),
                    AttachmentFileName = quoteVm.AttachmentFileName,
                    CreateDate = quoteVm.CreatedDate,
                    CreatedBy = quoteVm.CreatedBy
                };
                //model.AttachmentFileName = fileService.UploadFile(quoteVm.PostedFile.InputStream, null,
                //    quoteVm.PostedFile.FileName, quoteVm.PostedFile.ContentLength);
                _repo.Update(model);
                //_db.Entry(model).State = EntityState.Modified;
                _db.SaveChanges();
                return RedirectToAction("Index");
            }

            //invalid model lets return the View Model
            quoteVm.ProductList = new SelectList(_db.Products.AsQueryable(), "Id", "Description");
            quoteVm.CustomerSelectList = new SelectList(_db.Customers.AsQueryable(), "Id", "Name");
            return View(quoteVm);
        }
        public ActionResult Create() 
        {

            var model = new QuotationCreateVm();
            model.CustomerSelectList = new SelectList(_db.Customers.AsQueryable(), "Id", "Name");
            //model.ProductList = new SelectList(_db.Products.AsQueryable(), "Id", "Description");
            model.UnitOfMeasure = Enumerations.UnitOfMeasure.Pieces;
            return View(model);
        }

        [HttpPost]
        public ActionResult Create(QuotationCreateVm quoteVm)
        {
            //we'll move this mess to a service
            AmazonS3FileService fileService = new AmazonS3FileService(_curUserService);
            if (ModelState.IsValid)
            {
                var model = new Quotation()
                {
                    Product_Id = quoteVm.Product_Id,
                    Product_Description = quoteVm.Product_Description,
                    QuotedPrice = quoteVm.QuotedPrice,
                    Customer_Id = quoteVm.Customer_Id,
                    UnitOfMeasure = (int)quoteVm.UnitOfMeasure,
                    CustomerReference = quoteVm.CustomerReference,
                    Comments = quoteVm.Comments,
                    Status = Enumerations.QuotationStatus.Created.GetDescription()
                };

                if (!string.IsNullOrEmpty(model.AttachmentFileName))
                {
                    model.AttachmentFileName = fileService.UploadFile(quoteVm.PostedFile.InputStream, null,
                        quoteVm.PostedFile.FileName, quoteVm.PostedFile.ContentLength);
                }


                _db.Quotations.Add(model);
                _db.SaveChanges();
                return Redirect("Index");
            }

            //invalid model lets return the View Model
            quoteVm.ProductList = new SelectList(_db.Products.AsQueryable(), "Id", "Description");
            quoteVm.CustomerSelectList = new SelectList(_db.Customers.AsQueryable(), "Id", "Name");
            return View(quoteVm);
        }

        protected override void Dispose(bool disposing)
        {
            _db.Dispose();
            base.Dispose(disposing);
        }
    }
}

QuotationApp.Web/Views/Quotation/Create.cshtml
@model QuotationApp.Web.Models.QuotationCreateVm

@{
    ViewBag.Title = "Create";
}

<h2>Create New Quote</h2>


@using (Html.BeginForm("Create", "Quotation", FormMethod.Post, new { enctype = "multipart/form-data",  @class = "form-horizontal" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.Product_Id, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">

                @Html.EditorFor(model => model.Product_Id, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Product_Id, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Product_Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">

                @Html.EditorFor(model => model.Product_Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Product_Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UnitOfMeasure, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">

                @Html.EnumDropDownListFor(model => model.UnitOfMeasure, "--Select Unit Of Measure--", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.UnitOfMeasure, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Customer_Id, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
               
                @Html.DropDownListFor(model => model.Customer_Id, Model.CustomerSelectList, "--Select Customer--", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Customer_Id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CustomerReference, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CustomerReference, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CustomerReference, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PostedFile, new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                <div class="row">
                    <div class="col-md-12"><input type="file" name="PostedFile" id="input-id" multiple="multiple" /></div>
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Comments, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Comments, new { @class = "form-control", cols=60, rows=6 })
                @Html.ValidationMessageFor(model => model.Comments, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

QuotationApp.Web/Views/Quotation/Delete.cshtml
@model QuotationApp.Web.Models.QuotationDeleteVm

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>

    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dt>
            @Html.DisplayNameFor(model => model.Product_Id)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Product_Id)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Product_Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Product_Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.QuotedPrice)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.QuotedPrice)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedBy)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedBy)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

QuotationApp.Web/Views/Quotation/Edit.cshtml
@model QuotationApp.Web.Models.QuotationEditVm

@{
    ViewBag.Title = "Edit";
}

<h2>Edit Quotation</h2>


@using (Html.BeginForm("Edit", "Quotation", FormMethod.Post, new { enctype = "multipart/form-data", @class = "form-horizontal" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        @*<h4>QuotationEditVm</h4>*@
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)
        @Html.HiddenFor(model => model.CreatedBy)
        @Html.HiddenFor(model => model.CreatedDate)

        <div class="form-group">
            @Html.LabelFor(model => model.Product_Id, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Product_Id, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Product_Id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Product_Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Product_Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Product_Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MinOrderQty, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MinOrderQty, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MinOrderQty, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.UnitOfMeasure, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">

                @Html.EnumDropDownListFor(model => model.UnitOfMeasure, "--Select Unit Of Measure--", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.UnitOfMeasure, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.QuotedPrice, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.QuotedPrice, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.QuotedPrice, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.Customer_Id, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">

                @Html.DropDownListFor(model => model.Customer_Id, Model.CustomerSelectList, "--Select Customer--", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Customer_Id, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.CustomerReference, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CustomerReference, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CustomerReference, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Comments, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Comments, new { @class = "form-control", cols = 60, rows = 6 })
                @Html.ValidationMessageFor(model => model.Comments, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">

                @Html.EnumDropDownListFor(model => model.Status, "--Select Unit Of Measure--", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.UnitOfMeasure, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

QuotationApp.Web/Views/Quotation/Index.cshtml
@model IEnumerable<QuotationApp.Web.Models.QuotationIndexVm2>
@using GridMvc.Html
@using Newtonsoft.Json
@{
    
    ViewBag.Title = "Index";
    
}

<h2>Quotation List <small>You could filter using the icon filters in the column headers. Edit and Delete are on the left hand side of each row.</small></h2>



<p>
   @Html.ActionLink("Create New", "Create", null, new { @class = "btn btn-primary"})
   
</p>
@Html.Grid(Model).Columns(columns =>
           {
               columns.Add().Encoded(false).Sanitized(false).RenderValueAs(o =>
                   @<b>
                    @Html.ActionLink("Edit", "Edit", "Quotation", new { id = o.Id }, null)
                    <span> | </span>
                    @Html.ActionLink("Delete", "Delete", "Quotation", new { id = o.Id }, null)</b>
                );
               columns.Add(col => col.Id);
               columns.Add(col => col.Product_Id).Titled("Part Number");
               columns.Add(col => col.Product_Description).Titled("Part Description");
               columns.Add(col => col.QuotedPrice).Titled("Price");
               columns.Add(col => col.MinOrderQty).Titled("Min Order Qty");
               columns.Add(col => col.CustomerName).Titled("Customer");
               columns.Add(col => col.CustomerReference).Titled("Reference");
               columns.Add(col => col.CreatedBy).Titled("Created By");
               columns.Add(col => col.CreateDate).Titled("Created").Filterable(true).
                   SortInitialDirection(GridMvc.Sorting.GridSortDirection.Descending).Format("{0:MM/dd/yyyy}");
               columns.Add(col => col.Status);

           }).Filterable().Sortable(true).WithPaging(ViewBag.PageSize)



@section scripts{
    <script src="~/Scripts/gridmvc.min.js"></script> 
    <script src="~/Scripts/bootstrap-datepicker.js"></script>
    @*<script src="~/Scripts/knockout.mapping-latest.js"></script>*@

    <script type="text/javascript">

        $('.datepicker').datepicker({});

    </script>

}
@section styles{
  
    <link href="~/Content/Gridmvc.css" rel="stylesheet" />  
    <link href="~/Content/gridmvc.datepicker.min.css" rel="stylesheet" />
}

QuotationApp.Web/Views/Quotation/IndexJson.cshtml
@model IEnumerable<QuotationApp.Web.Models.QuotationIndexVm>
@using Newtonsoft.Json
@using QuotationApp.Web.Extensions
@{
    ViewBag.Title = "IndexJson";
}

<h2>IndexJson</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>

<table>
    <thead>
        <tr>
            <th>Gift name</th>
            <th>Price</th>
            <th />
        </tr>
    </thead>
    <tbody data-bind="foreach: quotations">
        <tr>
            <td><input class="required" data-bind="value: Id, uniqueName: true" /></td>
            <td><input class="required number" data-bind="value: CustomerName, uniqueName: true" /></td>
            <td><a href="#" data-bind="click: $root.RemoveQuote">Delete</a></td>
        </tr>
    </tbody>
</table>
<button data-bind="click: AddQuote">Add Gift</button>
<button data-bind="click: Save">Post to Server</button>



@section scripts{
    <script src="~/Scripts/gridmvc.min.js"></script>
    <script src="~/Scripts/knockout-3.3.0.js"></script>
    <script src="~/Scripts/knockout.mapping-latest.js"></script>

    <script type="text/javascript">
    $(function () {
        var QuotationModel = function(quotes){
            var self = this;
            self.quotations = ko.observableArray(quotes);
            self.AddQuote = function(){

                self.quotations.push({
                    Id: self.GenerateGuid(),
                    CustomerName:"",
                });

            }

            self.RemoveQuote = function (quote) {
                self.quotations.remove(quote);
            };

            self.GenerateGuid = function () {
                var guid = 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, function (c) {
                    var r = Math.random() * 16 | 0, v = c == 'x' ? r : (r & 0x3 | 0x8);
                    return v.toString(16);
                });
                return guid;
            }
            self.Save = function(){
                alert(self.quotations);
                $.ajax({
                    type: "POST",
                    url: "@Url.Action("Index2", "KnockoutGrid")",
                        data: ko.toJSON(self.quotations),
                        contentType: "application/json; charset=utf-8",
                        dataType: "json",
                        success: function (data) {
                            if (data) {
                                alert(ko.toJSON(data));
                            }
                        }
                    });
                }

        };

        viewModel = new QuotationModel(@Html.Raw(Model.ToJson()));
        ko.applyBindings(viewModel);

    });

    </script>

}
@section styles{

    <link href="~/Content/Gridmvc.css" rel="stylesheet" />
}